name: srt_ljh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/stations.json

fonts:
  - family: MyNotoSans
    fonts:
      - asset: fonts/NotoSansKR-Regular.ttf
      - asset: fonts/NotoSansKR-Medium.ttf
        weight: 500
      - asset: fonts/NotoSansKR-Bold.ttf
        weight: 700
      - asset: fonts/NotoSansKR-Black.ttf
        weight: 900